<?php
/**
 * ExtendedUserDataResponse
 *
 * PHP version 8.1.1
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.3
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the ExtendedUserDataResponse model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class ExtendedUserDataResponse 
{
        /**
     * Unique ID of the user
     *
     * @var string|null
     * @SerializedName("id")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $id;

    /**
     * Nickname of the user
     *
     * @var string|null
     * @SerializedName("username")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $username;

    /**
     * The profile picture of the user in data URI scheme.
     *
     * @var string|null
     * @SerializedName("picture")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $picture;

    /**
     * An introduction of the user.
     *
     * @var string|null
     * @SerializedName("about")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $about;

    /**
     * A short description about the project the user is currently working on.
     *
     * @var string|null
     * @SerializedName("currentlyWorkingOn")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $currently_working_on;

    /**
     * Amount of projects of the user
     *
     * @var int|null
     * @SerializedName("projects")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $projects;

    /**
     * Amount of users that follow this user
     *
     * @var int|null
     * @SerializedName("followers")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $followers;

    /**
     * Amount of users followed by this user
     *
     * @var int|null
     * @SerializedName("following")
     * @Assert\Type("int")
     * @Type("int")
     */
    protected ?int $following;

    /**
     * EMail of the user
     *
     * @var string|null
     * @SerializedName("email")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected ?string $email;

    /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->id = $data['id'] ?? null;
        $this->username = $data['username'] ?? null;
        $this->picture = $data['picture'] ?? null;
        $this->about = $data['about'] ?? null;
        $this->currently_working_on = $data['currently_working_on'] ?? null;
        $this->projects = $data['projects'] ?? null;
        $this->followers = $data['followers'] ?? null;
        $this->following = $data['following'] ?? null;
        $this->email = $data['email'] ?? null;
    }

    /**
     * Gets id.
     *
     * @return string|null
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets id.
     *
     * @param string|null $id  Unique ID of the user
     *
     * @return $this
     */
    public function setId(string $id = null): self
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Gets username.
     *
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * Sets username.
     *
     * @param string|null $username  Nickname of the user
     *
     * @return $this
     */
    public function setUsername(string $username = null): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Gets picture.
     *
     * @return string|null
     */
    public function getPicture(): ?string
    {
        return $this->picture;
    }

    /**
     * Sets picture.
     *
     * @param string|null $picture  The profile picture of the user in data URI scheme.
     *
     * @return $this
     */
    public function setPicture(string $picture = null): self
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * Gets about.
     *
     * @return string|null
     */
    public function getAbout(): ?string
    {
        return $this->about;
    }

    /**
     * Sets about.
     *
     * @param string|null $about  An introduction of the user.
     *
     * @return $this
     */
    public function setAbout(string $about = null): self
    {
        $this->about = $about;

        return $this;
    }

    /**
     * Gets currently_working_on.
     *
     * @return string|null
     */
    public function getCurrentlyWorkingOn(): ?string
    {
        return $this->currently_working_on;
    }

    /**
     * Sets currently_working_on.
     *
     * @param string|null $currently_working_on  A short description about the project the user is currently working on.
     *
     * @return $this
     */
    public function setCurrentlyWorkingOn(string $currently_working_on = null): self
    {
        $this->currently_working_on = $currently_working_on;

        return $this;
    }

    /**
     * Gets projects.
     *
     * @return int|null
     */
    public function getProjects(): ?int
    {
        return $this->projects;
    }

    /**
     * Sets projects.
     *
     * @param int|null $projects  Amount of projects of the user
     *
     * @return $this
     */
    public function setProjects(int $projects = null): self
    {
        $this->projects = $projects;

        return $this;
    }

    /**
     * Gets followers.
     *
     * @return int|null
     */
    public function getFollowers(): ?int
    {
        return $this->followers;
    }

    /**
     * Sets followers.
     *
     * @param int|null $followers  Amount of users that follow this user
     *
     * @return $this
     */
    public function setFollowers(int $followers = null): self
    {
        $this->followers = $followers;

        return $this;
    }

    /**
     * Gets following.
     *
     * @return int|null
     */
    public function getFollowing(): ?int
    {
        return $this->following;
    }

    /**
     * Sets following.
     *
     * @param int|null $following  Amount of users followed by this user
     *
     * @return $this
     */
    public function setFollowing(int $following = null): self
    {
        $this->following = $following;

        return $this;
    }

    /**
     * Gets email.
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * Sets email.
     *
     * @param string|null $email  EMail of the user
     *
     * @return $this
     */
    public function setEmail(string $email = null): self
    {
        $this->email = $email;

        return $this;
    }
}


