<?php
/**
 * MediaCategoryResponse.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.4
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use JMS\Serializer\Annotation\SerializedName;
use JMS\Serializer\Annotation\Type;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class representing the MediaCategoryResponse model.
 *
 * @author  OpenAPI Generator team
 */
class MediaCategoryResponse
{
  /**
   * ID of the category.
   *
   * @SerializedName("id")
   * @Assert\Type("int")
   * @Type("int")
   */
  protected ?int $id;

  /**
   * Name of the category.
   *
   * @SerializedName("name")
   * @Assert\Type("string")
   * @Type("string")
   */
  protected ?string $name;

  /**
   * Shows how important a category is (0 is the least priority).
   *
   * @SerializedName("priority")
   * @Assert\Type("int")
   * @Type("int")
   * @Assert\GreaterThanOrEqual(0)
   */
  protected ?int $priority;

  /**
   * Constructor.
   *
   * @param array|null $data Associated array of property values initializing the model
   */
  public function __construct(array $data = null)
  {
    $this->id = $data['id'] ?? null;
    $this->name = $data['name'] ?? null;
    $this->priority = $data['priority'] ?? null;
  }

  /**
   * Gets id.
   */
  public function getId(): ?int
  {
    return $this->id;
  }

  /**
   * Sets id.
   *
   * @param int|null $id ID of the category
   *
   * @return $this
   */
  public function setId(int $id = null): self
  {
    $this->id = $id;

    return $this;
  }

  /**
   * Gets name.
   */
  public function getName(): ?string
  {
    return $this->name;
  }

  /**
   * Sets name.
   *
   * @param string|null $name Name of the category
   *
   * @return $this
   */
  public function setName(string $name = null): self
  {
    $this->name = $name;

    return $this;
  }

  /**
   * Gets priority.
   */
  public function getPriority(): ?int
  {
    return $this->priority;
  }

  /**
   * Sets priority.
   *
   * @param int|null $priority Shows how important a category is (0 is the least priority)
   *
   * @return $this
   */
  public function setPriority(int $priority = null): self
  {
    $this->priority = $priority;

    return $this;
  }
}
