<?php
/**
 * Upload
 *
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Server\Model
 * @author   OpenAPI Generator team
 * @link     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 *
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Model;

use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation\Type;
use JMS\Serializer\Annotation\SerializedName;

/**
 * Class representing the Upload model.
 *
 * @package OpenAPI\Server\Model
 * @author  OpenAPI Generator team
 */
class Upload 
{
        /**
     * Checksum of the *.catrobat file
     *
     * @var string|null
     * @SerializedName("checksum")
     * @Assert\Type("string")
     * @Type("string")
     */
    protected $checksum;

    /**
     * *.catrobat file
     *
     * @var UploadedFile|null
     * @SerializedName("file")
     * @Assert\Type("UploadedFile")
     * @Type("UploadedFile")
     */
    protected $file;

    /**
     * @var OpenAPI\Server\Model\Flavor|null
     * @SerializedName("flavor")
     * @Assert\Type("OpenAPI\Server\Model\Flavor")
     * @Type("OpenAPI\Server\Model\Flavor")
     */
    protected $flavor;

    /**
     * Available tags
     *
     * @var OpenAPI\Server\Model\Tag[]|null
     * @SerializedName("tags")
     * @Assert\All({
     *   @Assert\Type("OpenAPI\Server\Model\Tag")
     * })
     * @Type("array<OpenAPI\Server\Model\Tag>")
     */
    protected $tags;

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->checksum = isset($data['checksum']) ? $data['checksum'] : null;
        $this->file = isset($data['file']) ? $data['file'] : null;
        $this->flavor = isset($data['flavor']) ? $data['flavor'] : null;
        $this->tags = isset($data['tags']) ? $data['tags'] : null;
    }

    /**
     * Gets checksum.
     *
     * @return string|null
     */
    public function getChecksum()
    {
        return $this->checksum;
    }

    /**
     * Sets checksum.
     *
     * @param string|null $checksum  Checksum of the *.catrobat file
     *
     * @return $this
     */
    public function setChecksum($checksum = null)
    {
        $this->checksum = $checksum;

        return $this;
    }

    /**
     * Gets file.
     *
     * @return UploadedFile|null
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Sets file.
     *
     * @param UploadedFile|null $file  *.catrobat file
     *
     * @return $this
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        return $this;
    }

    /**
     * Gets flavor.
     *
     * @return OpenAPI\Server\Model\Flavor|null
     */
    public function getFlavor()
    {
        return $this->flavor;
    }

    /**
     * Sets flavor.
     *
     * @param OpenAPI\Server\Model\Flavor|null $flavor
     *
     * @return $this
     */
    public function setFlavor(Flavor $flavor = null)
    {
        $this->flavor = $flavor;

        return $this;
    }

    /**
     * Gets tags.
     *
     * @return OpenAPI\Server\Model\Tag[]|null
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Sets tags.
     *
     * @param OpenAPI\Server\Model\Tag[]|null $tags  Available tags
     *
     * @return $this
     */
    public function setTags(array $tags = null)
    {
        $this->tags = $tags;

        return $this;
    }
}


