<?php
/**
 * NotificationsApiInterfaceTest
 * PHP version 7.1.3.
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.53
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * NotificationsApiInterfaceTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class NotificationsApiInterfaceTest extends WebTestCase
{
  /**
   * Setup before running any test cases.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Test case for notificationsCountGet.
   *
   * Count the number of unseen notifications.
   */
  public function testNotificationsCountGet()
  {
    $client = static::createClient();

    $path = '/notifications/count';

    $crawler = $client->request('GET', $path);
  }

  /**
   * Test case for notificationsGet.
   *
   * Get user notifications.
   */
  public function testNotificationsGet()
  {
    $client = static::createClient();

    $path = '/notifications';

    $crawler = $client->request('GET', $path);
  }

  /**
   * Test case for notificationsIdReadPut.
   *
   * Mark specified notification as read.
   */
  public function testNotificationsIdReadPut()
  {
    $client = static::createClient();

    $path = '/notifications/{id}/read';
    $pattern = '{id}';
    $data = $this->genTestData('\d+');
    $path = str_replace($pattern, $data, $path);

    $crawler = $client->request('PUT', $path);
  }

  /**
   * Test case for notificationsReadPut.
   *
   * Mark all notifications as read.
   */
  public function testNotificationsReadPut()
  {
    $client = static::createClient();

    $path = '/notifications/read';

    $crawler = $client->request('PUT', $path);
  }

  protected function genTestData($regexp)
  {
    $grammar = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
    $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
    $ast = $compiler->parse($regexp);
    $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

    return $generator->visit($ast);
  }
}
