<?php
/**
 * UserApiInterfaceTest
 * PHP version 7.1.3.
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.42
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Server\Tests\Api;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * UserApiInterfaceTest Class Doc Comment.
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class UserApiInterfaceTest extends WebTestCase
{
  /**
   * Setup before running any test cases.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Test case for userDelete.
   *
   * Delete user account.
   */
  public function testUserDelete()
  {
    $client = static::createClient();

    $path = '/user';

    $crawler = $client->request('DELETE', $path);
  }

  /**
   * Test case for userGet.
   *
   * Get your private user data.
   */
  public function testUserGet()
  {
    $client = static::createClient();

    $path = '/user';

    $crawler = $client->request('GET', $path);
  }

  /**
   * Test case for userIdGet.
   *
   * Get public user data.
   */
  public function testUserIdGet()
  {
    $client = static::createClient();

    $path = '/user/{id}';
    $pattern = '{id}';
    $data = $this->genTestData('^[a-zA-Z0-9\\-]+$');
    $path = str_replace($pattern, $data, $path);

    $crawler = $client->request('GET', $path);
  }

  /**
   * Test case for userPost.
   *
   * Register.
   */
  public function testUserPost()
  {
    $client = static::createClient();

    $path = '/user';

    $crawler = $client->request('POST', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
  }

  /**
   * Test case for userPut.
   *
   * Update User.
   */
  public function testUserPut()
  {
    $client = static::createClient();

    $path = '/user';

    $crawler = $client->request('PUT', $path, [], [], ['CONTENT_TYPE' => 'application/json']);
  }

  /**
   * Test case for usersSearchGet.
   *
   * Search for users.
   */
  public function testUsersSearchGet()
  {
    $client = static::createClient();

    $path = '/users/search';

    $crawler = $client->request('GET', $path);
  }

  protected function genTestData($regexp)
  {
    $grammar = new \Hoa\File\Read('hoa://Library/Regex/Grammar.pp');
    $compiler = \Hoa\Compiler\Llk\Llk::load($grammar);
    $ast = $compiler->parse($regexp);
    $generator = new \Hoa\Regex\Visitor\Isotropic(new \Hoa\Math\Sampler\Random());

    return $generator->visit($ast);
  }
}
