<?php
/**
 * DryRunTest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.19
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

/**
 * DryRunTest Class Doc Comment.
 *
 * @category    Class
 *
 * @description DryRun
 *
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPI\Server\Model\DryRun
 *
 * @internal
 */
class DryRunTest extends TestCase
{
  protected DryRun|MockObject $object;

  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass(): void {}

  /**
   * Setup before running each test case.
   */
  public function setUp(): void
  {
    $this->object = $this->getMockBuilder(DryRun::class)->getMockForAbstractClass();
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown(): void {}

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass(): void {}

  /**
   * @group integration
   *
   * @small
   */
  public function testTestClassExists(): void
  {
    $this->assertTrue(class_exists(DryRun::class));
    $this->assertInstanceOf(DryRun::class, $this->object);
  }

  /**
   * Test attribute "dry_run".
   *
   * @group unit
   *
   * @small
   */
  public function testPropertyDryRun(): void
  {
    $this->markTestSkipped('Test for property dry_run not implemented');
  }
}
