<?php
/**
 * FeaturedProjectResponseTest.
 *
 * PHP version 7.1.3
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.42
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * FeaturedProjectResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description FeaturedProjectResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class FeaturedProjectResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Test "FeaturedProjectResponse".
   */
  public function testFeaturedProjectResponse()
  {
    $testFeaturedProjectResponse = new FeaturedProjectResponse();
  }

  /**
   * Test attribute "id".
   */
  public function testPropertyId()
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName()
  {
  }

  /**
   * Test attribute "author".
   */
  public function testPropertyAuthor()
  {
  }

  /**
   * Test attribute "featured_image".
   */
  public function testPropertyFeaturedImage()
  {
  }
}
