<?php
/**
 * LoginResponseOKTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: 1.0.7
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * LoginResponseOKTest Class Doc Comment.
 *
 * @category    Class */
// * @description LoginResponseOK
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class LoginResponseOKTest extends \PHPUnit_Framework_TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Test "LoginResponseOK".
   */
  public function testLoginResponseOK()
  {
    $testLoginResponseOK = new LoginResponseOK();
  }

  /**
   * Test attribute "token".
   */
  public function testPropertyToken()
  {
  }
}
