<?php
/**
 * MediaPackageResponseTest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaPackageResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description MediaPackageResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class MediaPackageResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass(): void
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp(): void
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown(): void
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass(): void
  {
  }

  /**
   * Test "MediaPackageResponse".
   */
  public function testMediaPackageResponse(): void
  {
    $testMediaPackageResponse = new MediaPackageResponse();
  }

  /**
   * Test attribute "id".
   */
  public function testPropertyId(): void
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName(): void
  {
  }

  /**
   * Test attribute "url".
   */
  public function testPropertyUrl(): void
  {
  }

  /**
   * Test attribute "categories".
   */
  public function testPropertyCategories(): void
  {
  }
}
