<?php
/**
 * MediaCategoryTest.
 *
 * PHP version 5
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.39
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

/**
 * MediaCategoryTest Class Doc Comment.
 *
 * @category    Class */
// * @description MediaCategory
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class MediaCategoryTest extends \PHPUnit_Framework_TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Test "MediaCategory".
   */
  public function testMediaCategory()
  {
    $testMediaCategory = new MediaCategory();
  }

  /**
   * Test attribute "id".
   */
  public function testPropertyId()
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName()
  {
  }

  /**
   * Test attribute "priority".
   */
  public function testPropertyPriority()
  {
  }
}
