<?php
/**
 * MediaFileResponseTest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * MediaFileResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description MediaFileResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class MediaFileResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass(): void
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp(): void
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown(): void
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass(): void
  {
  }

  /**
   * Test "MediaFileResponse".
   */
  public function testMediaFileResponse(): void
  {
    $testMediaFileResponse = new MediaFileResponse();
  }

  /**
   * Test attribute "id".
   */
  public function testPropertyId(): void
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName(): void
  {
  }

  /**
   * Test attribute "flavors".
   */
  public function testPropertyFlavors(): void
  {
  }

  /**
   * Test attribute "packages".
   */
  public function testPropertyPackages(): void
  {
  }

  /**
   * Test attribute "category".
   */
  public function testPropertyCategory(): void
  {
  }

  /**
   * Test attribute "author".
   */
  public function testPropertyAuthor(): void
  {
  }

  /**
   * Test attribute "extension".
   */
  public function testPropertyExtension(): void
  {
  }

  /**
   * Test attribute "download_url".
   */
  public function testPropertyDownloadUrl(): void
  {
  }

  /**
   * Test attribute "size".
   */
  public function testPropertySize(): void
  {
  }

  /**
   * Test attribute "file_type".
   */
  public function testPropertyFileType(): void
  {
  }
}
