<?php
/**
 * NotificationsCountResponseTest.
 *
 * PHP version 7.1.3
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.58
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * NotificationsCountResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description NotificationsCountResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class NotificationsCountResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Test "NotificationsCountResponse".
   */
  public function testNotificationsCountResponse()
  {
    $testNotificationsCountResponse = new NotificationsCountResponse();
  }

  /**
   * Test attribute "total".
   */
  public function testPropertyTotal()
  {
  }

  /**
   * Test attribute "like".
   */
  public function testPropertyLike()
  {
  }

  /**
   * Test attribute "follower".
   */
  public function testPropertyFollower()
  {
  }

  /**
   * Test attribute "comment".
   */
  public function testPropertyComment()
  {
  }

  /**
   * Test attribute "remix".
   */
  public function testPropertyRemix()
  {
  }
}
