<?php
/**
 * NotificationContentTest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * NotificationContentTest Class Doc Comment.
 *
 * @category    Class */
// * @description NotificationContent
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class NotificationContentTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass(): void
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp(): void
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown(): void
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass(): void
  {
  }

  /**
   * Test "NotificationContent".
   */
  public function testNotificationContent(): void
  {
    $testNotificationContent = new NotificationContent();
  }

  /**
   * Test attribute "from".
   */
  public function testPropertyFrom(): void
  {
  }

  /**
   * Test attribute "from_name".
   */
  public function testPropertyFromName(): void
  {
  }

  /**
   * Test attribute "program".
   */
  public function testPropertyProgram(): void
  {
  }

  /**
   * Test attribute "program_name".
   */
  public function testPropertyProgramName(): void
  {
  }

  /**
   * Test attribute "avatar".
   */
  public function testPropertyAvatar(): void
  {
  }

  /**
   * Test attribute "remixed_program".
   */
  public function testPropertyRemixedProgram(): void
  {
  }

  /**
   * Test attribute "remixed_program_name".
   */
  public function testPropertyRemixedProgramName(): void
  {
  }

  /**
   * Test attribute "message".
   */
  public function testPropertyMessage(): void
  {
  }

  /**
   * Test attribute "prize".
   */
  public function testPropertyPrize(): void
  {
  }
}
