<?php
/**
 * ProjectResponseTest.
 *
 * PHP version 7.1.3
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.42
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProjectResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description ProjectResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class ProjectResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Test "ProjectResponse".
   */
  public function testProjectResponse()
  {
    $testProjectResponse = new ProjectResponse();
  }

  /**
   * Test attribute "id".
   */
  public function testPropertyId()
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName()
  {
  }

  /**
   * Test attribute "author".
   */
  public function testPropertyAuthor()
  {
  }

  /**
   * Test attribute "description".
   */
  public function testPropertyDescription()
  {
  }

  /**
   * Test attribute "version".
   */
  public function testPropertyVersion()
  {
  }

  /**
   * Test attribute "views".
   */
  public function testPropertyViews()
  {
  }

  /**
   * Test attribute "download".
   */
  public function testPropertyDownload()
  {
  }

  /**
   * Test attribute "private".
   */
  public function testPropertyPrivate()
  {
  }

  /**
   * Test attribute "flavor".
   */
  public function testPropertyFlavor()
  {
  }

  /**
   * Test attribute "uploaded".
   */
  public function testPropertyUploaded()
  {
  }

  /**
   * Test attribute "uploaded_string".
   */
  public function testPropertyUploadedString()
  {
  }

  /**
   * Test attribute "screenshot_large".
   */
  public function testPropertyScreenshotLarge()
  {
  }

  /**
   * Test attribute "screenshot_small".
   */
  public function testPropertyScreenshotSmall()
  {
  }

  /**
   * Test attribute "project_url".
   */
  public function testPropertyProjectUrl()
  {
  }

  /**
   * Test attribute "download_url".
   */
  public function testPropertyDownloadUrl()
  {
  }

  /**
   * Test attribute "filesize".
   */
  public function testPropertyFilesize()
  {
  }
}
