<?php
/**
 * ProjectsCategoryTest.
 *
 * PHP version 7.1.3
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.60
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * ProjectsCategoryTest Class Doc Comment.
 *
 * @category    Class */
// * @description ProjectsCategory
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class ProjectsCategoryTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass()
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp()
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown()
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass()
  {
  }

  /**
   * Test "ProjectsCategory".
   */
  public function testProjectsCategory()
  {
    $testProjectsCategory = new ProjectsCategory();
  }

  /**
   * Test attribute "type".
   */
  public function testPropertyType()
  {
  }

  /**
   * Test attribute "name".
   */
  public function testPropertyName()
  {
  }

  /**
   * Test attribute "projects_list".
   */
  public function testPropertyProjectsList()
  {
  }
}
