<?php
/**
 * UpdateUserErrorResponseTest.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   openapi-generator contributors
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.1.2
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Server\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateUserErrorResponseTest Class Doc Comment.
 *
 * @category    Class */
// * @description UpdateUserErrorResponse
/**
 * @author      openapi-generator contributors
 *
 * @see        https://github.com/openapitools/openapi-generator
 *
 * @internal
 * @coversNothing
 */
class UpdateUserErrorResponseTest extends TestCase
{
  /**
   * Setup before running any test case.
   */
  public static function setUpBeforeClass(): void
  {
  }

  /**
   * Setup before running each test case.
   */
  public function setUp(): void
  {
  }

  /**
   * Clean up after running each test case.
   */
  public function tearDown(): void
  {
  }

  /**
   * Clean up after running all test cases.
   */
  public static function tearDownAfterClass(): void
  {
  }

  /**
   * Test "UpdateUserErrorResponse".
   */
  public function testUpdateUserErrorResponse(): void
  {
    $testUpdateUserErrorResponse = new UpdateUserErrorResponse();
  }

  /**
   * Test attribute "email".
   */
  public function testPropertyEmail(): void
  {
  }

  /**
   * Test attribute "username".
   */
  public function testPropertyUsername(): void
  {
  }

  /**
   * Test attribute "password".
   */
  public function testPropertyPassword(): void
  {
  }

  /**
   * Test attribute "current_password".
   */
  public function testPropertyCurrentPassword(): void
  {
  }

  /**
   * Test attribute "picture".
   */
  public function testPropertyPicture(): void
  {
  }
}
