<?php
/**
 * ProjectsApiInterface
 * PHP version 5.
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.0.16
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use OpenAPI\Server\Model\Project;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * ProjectsApiInterface Interface Doc Comment.
 *
 * @category Interface
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */
interface ProjectsApiInterface
{
  /**
   * Sets authentication method pandaAuth.
   *
   * @param string $value value of the pandaAuth authentication method
   */
  public function setpandaAuth($value);

  /**
   * Operation projectProjectIdGet.
   *
   * Get the information of a project
   *
   * @param string $projectId       UUID/ID of any given project (required)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\Project
   */
  public function projectProjectIdGet(string $projectId, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsFeaturedGet.
   *
   * Get the currently featured projects
   *
   * @param string $platform        (optional)
   * @param string $maxVersion      (optional)
   * @param int    $limit           (optional, default to 20)
   * @param int    $offset          (optional, default to 0)
   * @param string $flavor          (optional)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\FeaturedProject[]
   */
  public function projectsFeaturedGet(string $platform = null, string $maxVersion = null, int $limit = 20, int $offset = 0, string $flavor = null, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsGet.
   *
   * Get projects
   *
   * @param string $projectType     (required)
   * @param string $acceptLanguage  (optional)
   * @param string $maxVersion      (optional)
   * @param int    $limit           (optional, default to 20)
   * @param int    $offset          (optional, default to 0)
   * @param string $flavor          (optional)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\Project[]
   */
  public function projectsGet(string $projectType, string $acceptLanguage = null, string $maxVersion = null, int $limit = 20, int $offset = 0, string $flavor = null, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsPost.
   *
   * Upload a catrobat program
   *
   * @param string       $acceptLanguage  (optional)
   * @param string       $checksum        Checksum of the *.catrobat file (optional)
   * @param UploadedFile $file            *.catrobat file (optional)
   * @param string       $flavor          Available flavors (optional)
   * @param string[]     $tags            Available tags (optional)
   * @param int          $responseCode    The HTTP response code to return
   * @param array        $responseHeaders Additional HTTP headers to return with the response ()
   */
  public function projectsPost(string $acceptLanguage = null, string $checksum = null, UploadedFile $file = null, string $flavor = null, array $tags = null, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsSearchGet.
   *
   * Search for programs associated with a keywords
   *
   * @param string $queryString     (required)
   * @param string $maxVersion      (optional)
   * @param int    $limit           (optional, default to 20)
   * @param int    $offset          (optional, default to 0)
   * @param string $flavor          (optional)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\Project[]
   */
  public function projectsSearchGet(string $queryString, string $maxVersion = null, int $limit = 20, int $offset = 0, string $flavor = null, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsUserGet.
   *
   * Get the projects of the logged in user
   *
   * @param string $maxVersion      (optional)
   * @param int    $limit           (optional, default to 20)
   * @param int    $offset          (optional, default to 0)
   * @param string $flavor          (optional)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\Project[]
   */
  public function projectsUserGet(string $maxVersion = null, int $limit = 20, int $offset = 0, string $flavor = null, &$responseCode, array &$responseHeaders);

  /**
   * Operation projectsUserUserIdGet.
   *
   * Get the public projects of a given user
   *
   * @param string $userId          UUID/ID of any given user (required)
   * @param string $maxVersion      (optional)
   * @param int    $limit           (optional, default to 20)
   * @param int    $offset          (optional, default to 0)
   * @param string $flavor          (optional)
   * @param int    $responseCode    The HTTP response code to return
   * @param array  $responseHeaders Additional HTTP headers to return with the response ()
   *
   * @return OpenAPI\Server\Model\Project[]
   */
  public function projectsUserUserIdGet(string $userId, string $maxVersion = null, int $limit = 20, int $offset = 0, string $flavor = null, &$responseCode, array &$responseHeaders);
}
