<?php
/**
 * StudioApiInterface.
 *
 * PHP version 8.1.1
 *
 * @category Class
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */

/**
 * Catroweb API.
 *
 * API for the Catrobat Share Platform
 *
 * The version of the OpenAPI document: v1.4.4
 * Contact: webmaster@catrobat.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Do not edit the class manually.
 */

namespace OpenAPI\Server\Api;

use OpenAPI\Server\Model\StudioUpdateRequest;

/**
 * StudioApiInterface Interface Doc Comment.
 *
 * @category Interface
 *
 * @author   OpenAPI Generator team
 *
 * @see     https://github.com/openapitools/openapi-generator
 */
interface StudioApiInterface
{
  /**
   * Sets authentication method BearerAuth.
   *
   * @param string|null $value value of the BearerAuth authentication method
   */
  public function setBearerAuth(?string $value): void;

  /**
   * Operation studioIdPut.
   *
   * Update a Studio
   *
   * @param string              $id                    (required)
   * @param StudioUpdateRequest $studio_update_request (required)
   * @param string              $accept_language       (optional, default to 'en')
   * @param int                 &$responseCode         The HTTP Response Code
   * @param array               $responseHeaders       Additional HTTP headers to return with the response ()
   */
  public function studioIdPut(
    string $id,
    StudioUpdateRequest $studio_update_request,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders
  ): array|object|null;

  /**
   * Operation studioPost.
   *
   * Create a new Studio
   *
   * @param StudioUpdateRequest $studio_update_request (required)
   * @param string              $accept_language       (optional, default to 'en')
   * @param int                 &$responseCode         The HTTP Response Code
   * @param array               $responseHeaders       Additional HTTP headers to return with the response ()
   */
  public function studioPost(
    StudioUpdateRequest $studio_update_request,
    string $accept_language,
    int &$responseCode,
    array &$responseHeaders
  ): array|object|null;
}
