name: Create Pull Request

on:
  push:
    branches:
      - develop

jobs:

  createPullRequest:

    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Clean old files
        run: |
          rm -rf .openapi-generator Api Controller DependencyInjection Model Resources Service Tests README.md

      - name: Open API code generation
        run:
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v5.0.0-beta generate -i local/catroweb.yaml -g php-symfony -p sortParamsByRequiredFlag=true -p skipFormModel=true -p variableNamingConvention=snake_case -p phpLegacySupport=false -o /local

      - name: Fix code style
        uses: docker://oskarstark/php-cs-fixer-ga:latest
        with:
          args: --allow-risky=yes

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated php-cs-fixer
          committer: Catrobot <Catrobot@catroweb.github.com>
          title: 'Bump autogenerated open API code'
          body: |
            Automatic Open API Code Generation

            This pull request is autogenerated using the latest catroweb.yml swagger specificatons
            from the develop branch and is updated automatically with every new change merged into the develop branch.

            - removes old autogenerated files
            - run open API generator (Symfony-Php)
            - fix code style (Php-cs-fixer)

            For more information checkout the action '.github/workflows/create_pull_request.yml'
          labels: automated, open-api-generator, php-cs-fixer

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
